### ISSUE TITLE
IPV6 loopback is not correctly detected and prioritized as loopback.

### ISSUE THREAD

**Issue by nkadel-skyhook** [customink-webops/hostsfile#62]
The automatic prioritizatgon of loopback addresses in entry.rb does not detect and prioritize IPv6 loopback addresses. This can cause IPv6 loopback to wind up below other addresses, and chaos can ensue in various edge cases.

**Comment by sethvargo** [comment]
It sounds like you have some very specific use cases and I'm not sure this cookbook is the right solution. I would be willing to review a PR to fix this functionality, but I think it might add additional complexity. As this is not a use-case that has previously been requested nor is it a personal use case of mine, it is unlikely I will be implementing this myself. You may want to look into writing your own cookbook or some of the other community cookbooks on the Chef Supermarket. 

All the code in this cookbook is open source and licensed under a license that permits you to copy it with proper attribution. Please feel free to use as much or as little of it as you would like :smile:!

**Comment by nkadel-skyhook** [comment]
I've submitted a patch for this, https://github.com/customink-webops/hostsfile/pull/63.
