### ISSUE TITLE
Cannot split long records

### ISSUE THREAD

**Issue by Cylindric** [customink-webops/hostsfile#66]
There is a maximum length of a single hosts entry, so in our current environment we simply split them:

    127.0.0.1 www.host1.com www2.host1.com www3.host1.com
    127.0.0.1 www.host2.com www2.host2.com www3.host2.com
    127.0.0.1 www.host3.com www2.host3.com www3.host3.com

How can I replicate this in hostsfile_entry?

I have tried creating multiple hostsfile_entries with the same IP, but they just overwrite each other. How can I either force every IP/Host combination to be it's own record, or group of records?

thanks

**Comment by sethvargo** [comment]
That is not something that is possible with this cookbook. I would recommend writing your own LWRP or just writing the `/etc/hosts` file manually yourself with `Chef::Util::FileEdit`.

This cookbook is designed to be used in large infrastructures with lots and lots of Chef recipes, so there is no mechanism to permit duplicate entries like this. Sorry.

**Comment by Cylindric** [comment]
Okay, thanks. Not sure what "lots of recipes" has to do with it, but I'll work something out.

thanks,

**Comment by sethvargo** [comment]
@Cylindric if you imagine a large organization (with multiple teams) all writing Chef cookbooks on a variety of sub-systems, it's very easy to step on toes.
