### ISSUE TITLE
Windows line endings

### ISSUE THREAD

**Issue by odlevakp** [customink-webops/hostsfile#70]
Using this cookbook on Linux and also Windows servers. On Windows it will leave the hosts file with unix line endings - nothing serious, since the system can us them correctly, more a convenience thing.

Is this even fixable?

**Comment by sethvargo** [comment]
https://github.com/customink-webops/hostsfile/pull/65 - once we test that, it'll be fixed.

**Comment by geoff-carr-bzy** [comment]
#
