### ISSUE TITLE
How to update IP address if they change?

### ISSUE THREAD

**Issue by jleonett** [customink-webops/hostsfile#72]
Let me start out by mentioning I am just starting to learn Chef and Ruby so this could be something obvious.

I have the initial hosts file creation working well using Chef Override Attributes.  Have used the append, create, and remove features. 

I suspect there is no built in ability to update an existing IP address to a new IP?  Simple Example:

1.2.3.4  myalias

I update my attribute from:

                "hostentries":{
                  "myalias": {
                    "ip": "1.2.3.4",
                    "hostname": "myalias"

To:

                "hostentries":{
                  "myalias": {
                    "ip": "5.6.7.8",
                    "hostname": "myalias"

I end up with both entries as such:
1.2.3.4  myalias
5.6.7.8  myalias

I have several ways to get around this but was wondering what might be a standard approach others have taken as this should be a fairly common task.

I have thought to build a hosts file in a separate location say /etc/hosts_chef and if there are any changes copy it over the original /etc/hosts.  Another less desirable option - have 2 lists of attributes one to create and others to remove so when one changes add the original to the remove list.

Any tips appreciated.  Thanks.

**Comment by vandadck** [comment]
I'm not familiar with this cookbook but seems like you could try:

hostsfile_entry '1.2.3.4' do
  ip_address '5.6.7.8'
  action :update
end

**Comment by jleonett** [comment]
True that might work.  But that would require me to make the change, then later after all the nodes have been updated to go in there and delete that piece of code.

Ideally looking for a way to make one change in one spot to do the updates.  My solution above with building a 2nd hosts file and only copying it over the original when there are changes will accomplish that but feels a bit messy.  I don't like my second option as it can be prone more to human error - IE someone updates it in the original list but does not put the original value in the "remove" list - which can break the system.

**Comment by sethvargo** [comment]
Hi @jleonett 

This is outside of the scope of this cookbook. Chef does not know the "prestate" and "poststate", so it's not possible to do a diff like that unfortunately.

It sounds like you want to manage the entire file. Why not just use a simple template resource that renders `/etc/hosts` directly from attributes instead then?

**Comment by jleonett** [comment]
Kind of what I was suspecting.  Thanks for confirming.  I am going to look into the template option as well.  Kind of new to Chef so I need to read up on the template capabilities.  Just have not used one yet.  As long as I can add to a template from multiple recipes it should work well.
