### ISSUE TITLE
No default compatibility with FIPS mode

### ISSUE THREAD

**Issue by 4bg0P** [customink-webops/hostsfile#83]
When using the cookbook with FIPS mode enabled on Windows 7, the `chef-client` command displays this error:

`sha512.c(81): OpenSSL internal error, assertion failed: Low level API call to digest SHA512 forbidden in FIPS mode!`

I troubleshot this error and I found out manipulator.rb library uses Digest library which is not compatible with the FIPS mode. 

I resolved it, using OpenSSL::Digest library instead of Digest library, to hash files.

**Comment by tas50** [comment]
Merged to master
